// P_BAF_EXTEND_ARES

EXTEND_TOP ~AR0700.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR0700.baf~
EXTEND_TOP ~AR0511.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR0511.baf~
EXTEND_TOP ~AR1106.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR1106.baf~
EXTEND_TOP ~AR0406.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR0406.baf~
EXTEND_TOP ~AR1900.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR1900.baf~
EXTEND_TOP ~AR1514.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR1514.baf~
EXTEND_TOP ~AR0300.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR0300.baf~
EXTEND_TOP ~AR0500.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR0500.baf~
EXTEND_TOP ~AR1200.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR1200.baf~
EXTEND_TOP ~AR0903.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR0903.baf~
EXTEND_TOP ~AR1904.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR1904.baf~
EXTEND_TOP ~AR1600.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR1600.baf~
EXTEND_TOP ~AR2100.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR2100.baf~
EXTEND_TOP ~AR1506.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR1506.baf~
EXTEND_TOP ~AR2601.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR2601.baf~
EXTEND_TOP ~AR1509.bcs~ ~Autumns_Twilight/Scripts/are_extend/AR1509.baf~
EXTEND_TOP ~BALDUR.bcs~ ~Autumns_Twilight/Scripts/BALDUR.baf~