// MultiCrossmod 01: Pai'Na y Sirene (Sin Hubelpot)
// P_DLG_BAF_ARE_MULTI01

COPY ~Autumns_Twilight/dialogue/crossmod/sirene/p_nbk14.BAM~ ~override~
COPY ~Autumns_Twilight/dialogue/crossmod/sirene/p_nbk14.itm~ ~override~
SAY NAME2 @10000119 /* Manto de la Perseverancia de Ilmater */
SAY DESC @10000120 /* */
SAY 0x106 @10000121 /* Sirene */

// Elixir
COPY ~Autumns_Twilight/dialogue/crossmod/paina/P_PAITM1.BAM~ ~override~
COPY ~Autumns_Twilight/dialogue/crossmod/paina/p_nbk13.itm~ ~override~
SAY NAME2 @9079212 /* Extract of Scolopendra */
SAY DESC @9079213 /* */
SAY 366 @9079214 /* */
SAY 0xd6 @9079215 /* */

COPY ~Autumns_Twilight/dialogue/crossmod/paina/P_PAIT1B.BAM~ ~override~
COPY ~Autumns_Twilight/dialogue/crossmod/paina/P_PAIT1C.BAM~ ~override~
COPY ~Autumns_Twilight/dialogue/crossmod/paina/p_paii1.spl~ ~override~
SAY 8 @9079216 /* Summon Venomous Scolopendra */ 
SAY 80 @9079217 /*  */

// PaiNa learns Summon Scarab
EXTEND_BOTTOM ~C0PaiNa.bcs~ ~Autumns_Twilight/dialogue/crossmod/paina/C0PaiNa.baf~


COMPILE EVALUATE_BUFFER 
	// Multi_1
	~Autumns_Twilight/Dialogue/crossmod/multi/1_paina_sirene/P_DuskJ.d~ 
	~Autumns_Twilight/Dialogue/crossmod/multi/1_paina_sirene/p_matut.d~ 
	~Autumns_Twilight/Dialogue/crossmod/multi/1_paina_sirene/p_danct2.d~ 
	~Autumns_Twilight/Dialogue/crossmod/multi/1_paina_sirene/p_dancti.d~ 
	~Autumns_Twilight/Dialogue/crossmod/multi/1_paina_sirene/p_demol2.d~ 
	~Autumns_Twilight/Dialogue/crossmod/multi/1_paina_sirene/P_FallJ.d~ 
	~Autumns_Twilight/Dialogue/crossmod/multi/1_paina_sirene/p_morgra.d~ 
	~Autumns_Twilight/Dialogue/crossmod/multi/1_paina_sirene/p_vorag.d~
	// Paina
	~Autumns_Twilight/Dialogue/crossmod/paina/p_belld.d~

	///////////////
	/// General////
	///////////////
		~Autumns_Twilight/Dialogue/P_BDusk.d~ 
		~Autumns_Twilight/Dialogue/P_Dusk.d~ 
		~Autumns_Twilight/Dialogue/P_DuskP.d~ 
		~Autumns_Twilight/Dialogue/summoning/p_jack.d~
		~Autumns_Twilight/Dialogue/summoning/p_sayang.d~
		~Autumns_Twilight/Dialogue/summoning/p_uma.d~
		~Autumns_Twilight/Dialogue/summoning/p_baba.d~
		~Autumns_Twilight/Dialogue/summoning/p_thiago.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_michel.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_demole.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_falon.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_cufati.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_ziben.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_coco.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_Sornhi.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_bell2.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_alabar.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_alaba2.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_bob.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_mike.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_kocha.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_komar.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_xeb.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_toxsan.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_tongas.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_serra.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_huron.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_valata.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_kaland.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_anthag.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_CelGh.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_matu2.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_miche2.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_Celin.d~
		~Autumns_Twilight/Dialogue/dusk_quests/p_dempid.d~
		~Autumns_Twilight/Characters/m3good_allies/p_coc2.d~
		~Autumns_Twilight/Characters/m3good_allies/p_cufat2.d~
		~Autumns_Twilight/Characters/m3good_allies/p_falo2.d~
		~Autumns_Twilight/Characters/m3good_allies/p_kayl2.d~
		~Autumns_Twilight/Characters/m3good_allies/p_zibe2.d~    
		~Autumns_Twilight/Dialogue/P_BFall.d~ 
		~Autumns_Twilight/Dialogue/P_Fall.d~ 
		~Autumns_Twilight/Dialogue/P_FallP.d~
		~Autumns_Twilight/Dialogue/fall_quests/p_andrew.d~
		~Autumns_Twilight/Dialogue/P_alendi.d~
		~Autumns_Twilight/Dialogue/summoning/p_kitoch.d~
		~Autumns_Twilight/Dialogue/fall_quests/p_iddx.d~
		~Autumns_Twilight/Dialogue/summoning/p_kakuto.d~
		~Autumns_Twilight/Dialogue/summoning/p_kakut2.d~
		~Autumns_Twilight/Dialogue/fall_quests/p_beast.d~
		~Autumns_Twilight/Dialogue/summoning/p_tabit.d~
		~Autumns_Twilight/Dialogue/summoning/p_daren.d~
		~Autumns_Twilight/Dialogue/summoning/p_sinna.d~
		~Autumns_Twilight/Dialogue/fall_quests/p_iceloc.d~
		~Autumns_Twilight/Dialogue/fall_quests/p_acrull.d~
		~Autumns_Twilight/Dialogue/fall_quests/p_gorm.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_meso.d~
		~Autumns_Twilight/Dialogue/p_alengh.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_philli.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_vidomi.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_tamika.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_tobias.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_xsi.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_nimbus.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_xsirum.d~
		~Autumns_Twilight/Dialogue/p_cho.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_qyl.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_vresh.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_tisiph.d~
		~Autumns_Twilight/Dialogue/rachnidra/P_GASS.d~
		~Autumns_Twilight/Dialogue/rachnidra/P_KANKRA.d~
		~Autumns_Twilight/Dialogue/rachnidra/P_LIPHIX.d~
		~Autumns_Twilight/Dialogue/rachnidra/P_ARTHRO.d~
		~Autumns_Twilight/Dialogue/rachnidra/p_skel.d~
		~Autumns_Twilight/Dialogue/fall_quests/p_gem.d~
		~Autumns_Twilight/Dialogue/fall_quests/p_gerwul.d~
		~Autumns_Twilight/Dialogue/P_Chon.d~
		~Autumns_Twilight/Dialogue/P_BChon.d~ 
		~Autumns_Twilight/Dialogue/P_ChonJ.d~ 
		~Autumns_Twilight/Dialogue/P_ChonP.d~
		~Autumns_Twilight/Dialogue/P_Alen.d~
		~Autumns_Twilight/Dialogue/P_BAlen.d~ 
		~Autumns_Twilight/Dialogue/P_AlenJ.d~ 
		~Autumns_Twilight/Dialogue/P_AlenP.d~
		~Autumns_Twilight/Dialogue/fall_quests/p_hakam.d~
		//~Autumns_Twilight/Dialogue/alendir_quests/P_ARCONT.d~	
		
			// Scripts
	~Autumns_Twilight/Scripts/P_DuskS.baf~
	~Autumns_Twilight/Scripts/P_DuskF.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_michel.baf~
	~Autumns_Twilight/Summonings/p_bellf.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_matut.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_falon.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_cufati.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_coco.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_ziben.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_huron.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_alabar.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_alaba2.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_bob.baf~
	~Autumns_Twilight/Scripts/dusk_chars/P_KOCHA.baf~
	~Autumns_Twilight/Scripts/dusk_chars/P_KOMAR.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_mike.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_serra.baf~
	~Autumns_Twilight/Scripts/dusk_chars/P_TONGAS.baf~
	~Autumns_Twilight/Scripts/dusk_chars/P_TOXSAN.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_xeb.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_anthag.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_kaland.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_sornhi.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_valata.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_matu2.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_dempid.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_dancti.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_demole.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_mephit.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_worg.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_CelGh.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_demol2.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_miche2.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_Celin.baf~
	~Autumns_Twilight/Scripts/dusk_chars/p_danct2.baf~
	~Autumns_Twilight/Scripts/are/P_AR14.baf~
	~Autumns_Twilight/Scripts/P_FallS.baf~ 
	~Autumns_Twilight/Scripts/P_FallF.baf~
	~Autumns_Twilight/Scripts/P_ChonF.baf~
	~Autumns_Twilight/Scripts/P_AlenF.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_kitoch.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_DAREN.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_sinna.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_VORAG.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_Andrew.baf~
	~Autumns_Twilight/Scripts/p_alendi.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_TABIT.baf~	
	~Autumns_Twilight/Scripts/P_ALEN2.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_ICELOC.baf~
	~Autumns_Twilight/Scripts/battle/P_AL2MAG.baf~
	~Autumns_Twilight/Scripts/fall_chars/p_acrull.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_kakut.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FAR1.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FAR2.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FAR3.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FAR4.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FAR5.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FAR6.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FA6B.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FAR7.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FAR8.baf~	
	~Autumns_Twilight/Scripts/baf_at_are/P_FA8B.baf~	
	~Autumns_Twilight/Scripts/baf_at_are/P_FA3B.baf~	
	~Autumns_Twilight/Scripts/baf_at_are/P_FAR9.baf~	
	~Autumns_Twilight/Scripts/baf_at_are/P_FA10.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FA11.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_F10B.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_F11B.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FA12.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_F12B.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FA13.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FA14.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FA15.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_FA16.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_GORM.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/P_TOBIAS.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/p_meso.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/P_PHILLI.baf~
	~Autumns_Twilight/Scripts/battle/P_FVAMP.baf~	
	~Autumns_Twilight/Scripts/rachnidra_chars/P_VIDOMI.baf~	
	~Autumns_Twilight/Scripts/rachnidra_chars/P_XSI.baf~	
	~Autumns_Twilight/Scripts/rachnidra_chars/P_NIMBUS.baf~	
	~Autumns_Twilight/Scripts/rachnidra_chars/P_TAMIKA.baf~	
	~Autumns_Twilight/Scripts/P_CHO.baf~	
	~Autumns_Twilight/Scripts/rachnidra_chars/P_QYL.baf~		
	~Autumns_Twilight/Scripts/rachnidra_chars/P_VRESH.baf~	
	~Autumns_Twilight/Scripts/rachnidra_chars/P_RASK.baf~
	~Autumns_Twilight/Scripts/battle/P_DFSCHY.baf~	
	~Autumns_Twilight/Scripts/battle/P_DFSCHZ.baf~	
	~Autumns_Twilight/Scripts/rachnidra_chars/P_TISIPH.baf~	
	~Autumns_Twilight/Scripts/battle/p_weavfr.baf~	
	~Autumns_Twilight/Scripts/battle/p_weavcd.baf~	
	~Autumns_Twilight/Scripts/battle/p_weavac.baf~	
	~Autumns_Twilight/Scripts/battle/p_weavth.baf~	
	~Autumns_Twilight/Scripts/battle/p_spsw1.baf~	
	~Autumns_Twilight/Scripts/p_choc.baf~
	~Autumns_Twilight/Scripts/p_choc2.baf~
	~Autumns_Twilight/Scripts/p_choc3.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/p_liphix.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/p_arthro.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/p_gass.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/p_kankra.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/p_meso2.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/P_SKEL.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/P_MORGRA.baf~
	~Autumns_Twilight/Scripts/rachnidra_chars/P_MORGR2.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_GEM.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_2601.baf~
	~Autumns_Twilight/Scripts/fall_chars/P_GERWUL.baf~
	~Autumns_Twilight/Scripts/p_chons.baf~
	~Autumns_Twilight/Scripts/p_alens.baf~
	~Autumns_Twilight/Scripts/summoning/p_jack.baf~
	~Autumns_Twilight/Scripts/summoning/p_uma.baf~
	~Autumns_Twilight/Scripts/summoning/p_baba.baf~
	~Autumns_Twilight/Scripts/summoning/p_thiago.baf~

	
	//NEW AREAS
	~Autumns_Twilight/Scripts/baf_at_are/P_IP01.baf~
	~Autumns_Twilight/Scripts/baf_at_are/P_IP11.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRAN1.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRAN2.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRAN3.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRAN4.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRAN5.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRAN6.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRAN7.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRAN8.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRAN9.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA10.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA11.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA12.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA13.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA14.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA15.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA16.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA17.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA18.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA19.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA20.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA21.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA22.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA23.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA24.baf~
	~Autumns_Twilight/Scripts/transitions/P_FTRA25.baf~
	~Autumns_Twilight/Scripts/triggers/P_CHOTR1.baf~
	~Autumns_Twilight/Scripts/triggers/P_CHOTR2.baf~
	~Autumns_Twilight/Scripts/triggers/P_SKETR1.baf~
	~Autumns_Twilight/Scripts/triggers/P_FALTR1.baf~	
	~Autumns_Twilight/Scripts/kits/P_SHUNSU.baf~	
		
		// Crossmods Dialogues
		COMPILE ~%MOD_FOLDER%/dialogue/crossmod/paina/BC0Paina.d~
				~%MOD_FOLDER%/dialogue/crossmod/sirene/BC0Sire2.d~
