// Hotkey configurable
IF
HotKey(K)
THEN
RESPONSE #100
StartCutSceneMode()
StartCutScene("P_ChonF")
END

IF
Global("P_Chon_UpdateK","GLOBAL",1)
THEN
RESPONSE #100
Wait (6)
SetGlobal("P_Chon_UpdateK","GLOBAL",0)
END

IF
Global("P_ChoUpdateKit","GLOBAL",0)
THEN
RESPONSE #100
CreateItem ("P_DREAS1",1,1,1)
UseItem ("P_DREAS1", Myself)
DestroyItem("P_DREAS1")
AddKit("P_WGUA")
SetGlobal("P_ChoUpdateKit","GLOBAL",1)
END
